config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  namespace :admin do
    root 'top#dash_board'
    get 'login' => 'sessions#new', as: :login
    post 'session' => 'sessions#create', as: :session
    delete 'session' => 'sessions#destroy'
    resources :portfolios, except: %i[show]
    resources :articles
    resources :users, only: %i[edit update]
    resources :article_images, only: %i[create destroy]
  end
  namespace :visitor, path: '' do
    root 'top#index'
    resources :portfolios, only: %i[index show]
    resources :articles, only: %i[show]
  end
end

app/controllers/admin/top_controller.rb
class Admin::TopController < Admin::Base
  def dash_board
    @articles = Article.all
    @portfolios = Portfolio.all
  end
end

app/controllers/visitor/articles_controller.rb
class Visitor::ArticlesController < ApplicationController
  def show
    @article = Article.find(params[:id])
    if @article.unpublished?
      redirect_to :visitor_root
    end
  end
end

app/controllers/visitor/portfolios_controller.rb
class Visitor::PortfoliosController < ApplicationController
  def index
    @portfolios = Portfolio.order(created_at: :desc).page(params[:page])
  end

  def show
    @portfolio = Portfolio.find(params[:id])
  end
end

app/controllers/visitor/top_controller.rb
class Visitor::TopController < ApplicationController
  def index
    if params[:tag]
      @articles = Tag.find(params[:tag]).articles.includes(:tags)
    else
      @articles = Article.order(published_at: :desc).includes(:tags)
    end
    @articles = @articles.page(params[:page])
  end
end

app/helpers/admin/top_helper.rb
module Admin::TopHelper
end

app/helpers/visitor/articles_helper.rb
module Visitor::ArticlesHelper
end

app/helpers/visitor/portfolios_helper.rb
module Visitor::PortfoliosHelper
end

app/helpers/visitor/top_helper.rb
module Visitor::TopHelper
end

app/views/visitor/top/index.html.erb
<div class="wrapper">
  
  <div class="article_area">
    <%= paginate @articles %>
    <div class="article_wrap">
      <% @articles.each do |article| %>
        <div class='article_card'>
          <div class="article_image">
            <% unless article.thumbnail.url.nil?  %>
              <%= link_to [:visitor, article] do %>
                <%= image_tag(article.thumbnail.url) %>
              <% end %>
            <% end %>
          </div>
          
          <%= link_to article.title, [:visitor, article] %>
          <div class="publish_wrap">
            <i class="far fa-clock"></i>
            <%= article.published_at.strftime("%Y/%m/%d") %>
          </div>
          <div class="tags-wrap">
            <% article.tags.each do |tag| %>
              <span class="tag">
                <%= link_to  "#{tag.name}", visitor_root_path(tag: tag.id) %>
              </span>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
    <%= paginate @articles %>
  </div>
  
</div>