config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  namespace :admin do
    root 'top#dash_board'
    get 'login' => 'sessions#new', as: :login
    post 'session' => 'sessions#create', as: :session
    delete 'session' => 'sessions#destroy'
    resources :portfolios, except: %i[show]
    resources :articles
    resources :users, only: %i[edit update]
    resources :article_images, only: %i[create destroy]
  end
  namespace :visitor, path: '' do
    root 'top#index'
    resources :portfolios, only: %i[index show]
    resources :articles, only: %i[show]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :taggings
  has_many :tags, through: :taggings
  validates :title, presence: true
  validates :content, presence: true
  validates :thumbnail, presence: true
  mount_uploader :thumbnail, ThumbnailUploader

  def self.published_articles
    where('published_at <= ?', DateTime.now)
  end

  def unpublished?
    DateTime.now < published_at
  end

  def save_tags(tags)
    current_tags = self.tags.pluck(:name) unless self.tags.nil?
    old_tags = current_tags - tags
    new_tags = tags - current_tags

    # Destroy old taggings:
    old_tags.each do |old_tagname|
      self.tags.delete Tag.find_by(name:old_tagname)
    end

    # Create new taggings:
    new_tags.each do |new_tagname|
      post_tag = Tag.find_or_create_by(name:new_tagname)
      self.tags << post_tag
    end
  end
end

app/models/article_image.rb
class ArticleImage < ApplicationRecord
  mount_uploader :image, ContentUploader
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  mount_uploader :image, PortfolioUploader
  validates :name, presence: true
  validates :image, presence: true
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings
  has_many :articles, through: :taggings
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :article
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :image, UserUploader
  validates :email, presence: true
  def password=(raw_password)
    if raw_password.kind_of?(String)
      self.hashed_password = BCrypt::Password.create(raw_password)
    elsif raw_password.nil?
      self.hashed_password = nil
    end
  end

  def update_user_info(params)
    self.password = params[:new_password] if params[:new_password].present?
    self.email = params[:email]
    save
  end
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < Admin::Base
  def index
    if params[:tag]
      @articles = Tag.find(params[:tag]).articles.includes(:tags)
    else
      @articles = Article.order(published_at: :desc).includes(:tags)
    end
    @articles = @articles.page(params[:page])
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    tag_list = params[:tags].split(',')
    if @article.save
      @article.save_tags(tag_list)
      flash.notice = '記事を作成しました。'
      redirect_to :admin_articles
    else
      flash.now.alert = '記事を作成できませんでした。'
      render action: 'new'
    end
  end

  def edit
    @article = Article.find(params[:id])
    @tag_list = @article.tags.pluck(:name).join(',')
  end

  def update
    @article = Article.find(params[:id])
    tag_list = params[:tags].split(',')
    if @article.update(article_params)
      @article.save_tags(tag_list)
      flash.notice = '記事を更新できました。'
      redirect_to :admin_articles
    else
      flash.now.alert = '記事を更新できませんでした。'
      render action: 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    flash.notice = '記事を削除しました。'
    redirect_to :admin_articles
  end

  private
  def article_params
    params.require(:article).permit(:title, :content, :thumbnail, :published_at, :tags)
  end

end

app/controllers/admin/base.rb
class Admin::Base < ApplicationController
  before_action :authenticate

  private def authenticate
    unless current_admin
      redirect_to :admin_login
    end
  end

  private def current_admin
    if session[:administrator_id]
      @current_admin ||=
        User.find(session[:administrator_id])
    end
  end

  helper_method :current_admin
end

app/controllers/admin/sessions_controller.rb
class Admin::SessionsController < Admin::Base
  skip_before_action :authenticate
  def new
    if current_admin
      redirect_to :admin_root
    else
      @form = Admin::LoginForm.new
      render action: 'new'
    end
  end

  def create
    @form = Admin::LoginForm.new(admin_login_params)
    if @form.email.present?
      admin = User.find_by('LOWER(email)=?', @form.email.downcase)
    end
    if Admin::Authenticator.new(admin).authenticate(@form.password)
      flash.notice = '管理者としてログインしました。'
      session[:administrator_id] = admin.id
      redirect_to :admin_root
    else
      flash.now.alert = 'ログインできませんでした。'
      render action: 'new'
    end
  end

  def destroy
    session.delete(:administrator_id)
    flash.notice = 'ログアウトしました。'
    redirect_to :admin_root
  end

  private
  def admin_login_params
    params.require(:admin_login_form).permit(:email, :password)
  end
end

app/controllers/admin/top_controller.rb
class Admin::TopController < Admin::Base
  def dash_board
    @articles = Article.all
    @portfolios = Portfolio.all
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::Base

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_user_info(user_params)
      flash.notice = '更新できました。'
      redirect_to :admin_root
    else
      flash.now.alert = '更新できませんでした。'
      render action: 'edit'
    end
  end

  private
  def user_params
    params.require(:user).permit(
      :email, :new_password
    )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  layout :set_layout

  private def set_layout
    if params[:controller].match(%r{\A(visitor|admin)/})
      Regexp.last_match[1]
    else
      'visitor'
    end
  end
end

app/controllers/visitor/articles_controller.rb
class Visitor::ArticlesController < ApplicationController
  def show
    @article = Article.find(params[:id])
    if @article.unpublished?
      redirect_to :visitor_root
    end
  end
end

app/controllers/visitor/top_controller.rb
class Visitor::TopController < ApplicationController
  def index
    if params[:tag]
      @articles = Tag.find(params[:tag]).articles.includes(:tags)
    else
      @articles = Article.order(published_at: :desc).includes(:tags)
    end
    @articles = @articles.page(params[:page])
  end
end

app/helpers/admin/article_images_helper.rb
module Admin::ArticleImagesHelper
end

app/helpers/admin/articles_helper.rb
module Admin::ArticlesHelper
end

app/helpers/admin/portfolios_helper.rb
module Admin::PortfoliosHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/admin/top_helper.rb
module Admin::TopHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def document_title
    if @title.present?
      "#{@title}-KIROKU"
    else
      'KIROKU'
    end
  end
end

app/helpers/visitor/articles_helper.rb
module Visitor::ArticlesHelper
end

app/helpers/visitor/portfolios_helper.rb
module Visitor::PortfoliosHelper
end

app/helpers/visitor/top_helper.rb
module Visitor::TopHelper
end

app/views/admin/articles/_form.html.erb
<div class="form-group">
  <% if a.thumbnail.present? %>
    <%= image_tag(a.thumbnail.url) %>
  <% end %>
  <br>
  <%= f.label :thumbnail, "サムネイル" %>
  <%= f.file_field :thumbnail, class: 'form-control' %>
</div>
<div >
  <%= f.label :published_at, "公開日", class:'form-label' %>
  <div class='form-row'>
    <%= f.datetime_select(:published_at, {default: DateTime.now}, class: 'form-control col') %>
  </div>
</div>
<div class="form-group">
  <%= f.label :title, "タイトル" %>
  <%= f.text_field :title, class: 'form-control' %>
</div>
<div class='form-group'>
  <div id='tag-field'>
    <%= label :content, 'タグ(,区切りで入力)', class: 'action_text_label' %> <br>
    <p><small>例：ゼミ,R,データ加工</small></p>
    <ul id='tag-input'></ul>
    <%= hidden_field_tag :hidden_tag, @tag_list %>
  </div>
</div>
<div>
  <%= f.label :content, "本文" %>
  <%= f.text_area :content, id: 'summernote' %>
  <%= hidden_field_tag :article_id, a.id %>
</div>

app/views/admin/articles/edit.html.erb
<div class="form_wrapper">
<% @title = '記事更新' %>
  <div class="form">
    <h1><%= @title %></h1>
    <%= form_with model: @article, url: [:admin, @article] do |f| %>
    <%= render 'form', f: f, a: @article %>
    <div class="buttons">
      <%= f.submit '更新' %>
      <%= link_to  "キャンセル", :admin_articles %>
    </div>
    <% end %>
  </div>
</div>

app/views/admin/articles/index.html.erb
<% @title = '記事一覧' %>
<%= link_to  "追加", :new_admin_article, class: 'btn btn-dark' %>
<div class="article_area">
  <%= paginate @articles %>
  <h1><%= @title %></h1>
  <div class="article_wrap">
    <% @articles.each do |article| %>
      <div class='article_card'>
        <div class="article_image">
          <% unless article.thumbnail.url.nil?  %>
            <%= image_tag(article.thumbnail.url) %>
          <% end %>
        </div>
        
        <h4><%= link_to article.title, [:admin, article] %></h4>
        <div class="publish_wrap">
          <i class="far fa-clock"></i>
          <%= article.published_at.strftime("%Y/%m/%d") %>
          <%= content_tag(:span, '未公開', class: 'unpublish-tag') if article.unpublished? %>
        </div>
        <div class="actions">
          <%= link_to  "編集", [:edit, :admin, article] %>
          <%= link_to  "削除", [:admin, article], method: :delete,
          data: { confirm: '本当に削除しますか？' } %>
        </div>
        <div class="tags-wrap">
          <% article.tags.each do |tag| %>
            <span class="tag">
              <%= link_to  "#{tag.name}", admin_articles_path(tag: tag.id) %>
            </span>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
  <%= paginate @articles %>
</div>

<%= link_to  "追加", :new_admin_article, class: 'btn btn-dark' %>

app/views/admin/articles/new.html.erb
<div class="form_wrapper">
<% @title = '記事投稿' %>
  <div class="form">
    <h1><%= @title %></h1>
    <%= form_with model: @article, url: :admin_articles do |f| %>
    <%= render 'form', f: f, a: @article %>
    <div class="buttons">
      <%= f.submit '投稿' %>
      <%= link_to  "キャンセル", :admin_articles %>
    </div>
    <% end %>
  </div>
</div>

app/views/admin/articles/show.html.erb
<%= link_to  "編集", [:edit, :admin, @article], class: 'btn btn-dark' %>

<div class="article">
  <h1><%= @article.title %></h1>
  <div class="article_publish_wrap">
    <i class="far fa-clock"></i>
    <%= @article.published_at.strftime('%Y/%m/%d') %>
  </div>
  <div class="article_image_wrap">
    <%= image_tag(@article.thumbnail.url) %>
  </div>
  <hr>
  <div class="article_content">
    <%= sanitize @article.content %>
  </div>
</div>
<%= link_to  "編集", [:edit, :admin, @article], class: 'btn btn-dark' %>